---
- name: Install Argon One Tools
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Download install script
      get_url:
        url: https://download.argon40.com/argon1.sh
        dest: /opt/argon1.sh
        mode: '0755'

    - name: Install Argon tools
      command:
        cmd: /opt/argon1.sh
        creates: /lib/systemd/system/argononed.service
      register: install_argon


    - name: restart server
      shell: sleep 2 && shutdown -r now "Argon Tools Install triggered"
      async: 1
      poll: 0
      ignore_errors: true
      when: install_argon.changed

    - name: waiting for server to come back
      local_action: wait_for host={{ inventory_hostname }}
                    state=started
                    delay=30
                    timeout=300
                    port=22
      become: false
      when: install_argon.changed
