---
- name: Reboot CyberPi
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: restart server
      shell: sleep 2 && shutdown -r now
      async: 1
      poll: 0
      ignore_errors: true

    - name: waiting for server to come back
      local_action: wait_for host={{ inventory_hostname }}
                    state=started
                    delay=30
                    timeout=300
                    port=22
      become: false
